var quotes =['“Don’t practice until you get it right.  Practice until you can’t get it wrong.” – Anonymous',
'“May the best day of your past be the worst day of your future.” – Anonymous', '”A mind that is stretched by a new experience can never go back to its old dimensions.” – Oliver Wendell Holmes Jr.','“If I had asked people what they wanted, they would have said, ‘Faster horses’.” – Henry Ford', '“A tiger doesn’t lose sleep over the opinion of sheep.” – Shahir Zag', '“Kindness is a language that the deaf can hear and the blind can see.” – Mark Twain', '“If opportunity doesn’t knock, build a door.” – Milton Berle', '“I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.” – Maya Angelou', '“There ain’t no problem that some other dude didn’t have 1,000 years ago.” – Will Smith','“Education is not the filling of a pail, but the lighting of a fire.” – W.B. Yeats','“Pay attention to your enemies, for they are the first to discover your mistakes.” – Antisthenes', '“Failure is simply the opportunity to begin again, this time more intelligently.” – Henry Ford', '“The greatest mistake you can ever make in life is to be continually fearing that you will make one.” – Ellen Hubbard', '“Sometimes I want to ask God why He allows poverty, famine, and injustice when He could do something about it, but I’m afraid he might just ask me the same question.” – Abdu’l-Baha', '“As men grow old enough to look back on their lives, any pain they have does not come from the things at which they failed, but the things they never tried.” – Antwan McLean','“Courage isn’t having the strength to go on – it is going on when you don’t have strength.”  – Napoleon Bonaparte', '“If you don’t turn your life into a story, you just become a part of someone else’s story.” – Terry Pratchett','“When you realize how perfect everything is, you will tilt your head back and laugh at the sky.” – Buddha','“What would you attempt to do if you knew you could not fail?” – Robert Schuller', '“Be more concerned with your character than your reputation, because your character is what you really are, while your reputation is merely what others think you are.” – John Wooden','“A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.” – Winston Churchill','“I don’t know what frightens me more, the power that crushes us, or our endless ability to endure it.” – Gregory David Roberts','”Today I do what others won’t, so that tomorrow I can accomplish what others don’t.” –Jerry Rice','“Don’t confuse comfort with happiness.” – Dean Karnazes','“Certain things catch your eye, but pursue only those that capture the heart.” – Ancient Indian Proverb','“You cannot swim for new horizons until you have courage to lose sight of the shore.” –William Faulkner','“Know the rules well, so you can break them effectively.” – Dalai Lama','“Remember that happiness is a way of travel, not a destination.” – Roy L. Goodman'];
max = quotes.length;
ran =  Math.floor(Math.random()*(max - 0 + 1));
$('.container').html(quotes[ran]);
 $('#changer').click(function(){
 var num = Math.floor(Math.random()*(max - 0 + 1));
  $('.container').html(quotes[num]);
});
